### ISSUE TITLE
Exceptions after PhpStorm update to 2017.3

### ISSUE THREAD

**Issue by codexp** [rentalhost/laravel-insight#30]
Exception:

`com.jetbrains.php.lang.psi.elements.Method.getReturnType()Lcom/intellij/psi/PsiElement;
java.lang.NoSuchMethodError: com.jetbrains.php.lang.psi.elements.Method.getReturnType()Lcom/intellij/psi/PsiElement;
	at net.rentalhost.idea.laravelInsight.fluent.UsingAsTypeInspection$1.visitPhpMethod(UsingAsTypeInspection.java:34)
	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:85)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:309)
	at com.intellij.concurrency.ApplierCompleter.d(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1122)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:230)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:534)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:479)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by phiterf** [comment]
Same thing happening to me.
![image](https://user-images.githubusercontent.com/12252332/33834233-6b3c2fa2-de69-11e7-8920-1d20601e96e7.png)

**Comment by rentalhost** [comment]
Sorry guys. I am having problem with IDEA, so I can't run tests in any plugin for now. I will try contact Jetbrains to understand what the error means (something like "restart IDEA to reindex", but it doesn't works).

**Comment by phiterf** [comment]
This is also making the rest of the inspections to fail. I get undefined constants / variables where there shouldn't be, and they get fixed by disabling the plugin.

I hope you manage to fix this soon.

Thanks for the plugin, it's very helpful.

**Comment by fhugas** [comment]
Ran into the same issue here after upgrade, had to deactivate laravel-insight to make the exceptions stop bothering me. Luckily I saw this before I upgraded PhpStorm on my primary machine.

**Comment by rentalhost** [comment]
Guys, I promise that this weekend I will give all efforts to make it available again. I don't know that my plugin is too popular - actually I thought that just me have used that. haha Sorry too much! But you will have it again soon!

**Comment by phiterf** [comment]
Your plugin is amazing dude, and it's a must have!
It has been downloaded 14k times according to the plugin repository.

Thank you very much for it.

**Comment by rentalhost** [comment]
Wow! Last time that I seen it was about 200. :open_mouth: I am very happy and surprised with that. I have some [new features](https://github.com/rentalhost/laravel-insight/issues) to implement yet, and it will be decisive to I keep working on it. :smiley: Thank a lot by the confidence.

**Comment by youyi1314** [comment]
same here~ thanks for your plugin, 
will wait your update =)

**Comment by rentalhost** [comment]
Thank you for wait. I have commited today a new version `0.3.3` to Jetbrains Plugins repository. It should comes in two days and will fix this issue.

**Closing:** fixed.

**Comment by phiterf** [comment]
I tried downloading the .jar and installing manually, I keep getting the same error. Should I just wait for it to get updated in the repository?

**Comment by rentalhost** [comment]
@phiterf Could you check if the installed version is 0.3.3?

**Comment by phiterf** [comment]
Yeah it's on 3.0

Here are some images:

![image](https://user-images.githubusercontent.com/12252332/34108212-5df4c732-e3e6-11e7-9824-c83a1694e0ea.png)

![image](https://user-images.githubusercontent.com/12252332/34108244-7e6f6526-e3e6-11e7-8800-ffc7380e89f6.png)

![image](https://user-images.githubusercontent.com/12252332/34108259-9085455a-e3e6-11e7-99f4-4033b429a047.png)


The other laravel related plugins I have is Laravel Plugin and Blade Support.

**Comment by rentalhost** [comment]
@phiterf Oh, that is bad. I need compile it from IDEA 2017.3, but it doesn't works currently for me. So I will disable support to this feature for now while I wait a response from Jetbrains. Thanks for help.

**Comment by rentalhost** [comment]
@phiterf Could you please try the following compilation (extract it first)? It is a reduced version of plugin, removing the support for return types (eg. `function x(): Fluent`, the `Fluent` will not be checked anymore, temporarily).

[laravel-insight.zip](https://github.com/rentalhost/laravel-insight/files/1568741/laravel-insight.zip)

**Comment by phiterf** [comment]
Just downloaded and installed  it. So far no errors. I'll keep on working normally and if anything pops up I'll reply here.

**Comment by rentalhost** [comment]
@phiterf Okay, I will wait until end of day, if no errors occurs, I will push a new version to Jetbrains repository. Thanks for support.

**Comment by rentalhost** [comment]
Pushing `0.3.3.1` with last fix. It will disable the  *return type support* temporarily until IntelliJ IDEA 2017.3.2 being released. Plugin update should be available until two business days.

**Comment by phiterf** [comment]
rentalhost can you update the readme of this project here explaining what the plugin does? (like what features it has to improve the ide)

**Comment by rentalhost** [comment]
@phiterf I can swear there was one. I'll arrange it! 

In the meantime, you can check all available features on [Official Wiki](https://github.com/rentalhost/laravel-insight/wiki) and know about releases on [Releases Page](https://github.com/rentalhost/laravel-insight/releases).

**Comment by phiterf** [comment]
Oh thank you. I tried entering the wiki once but I didn't notice the right side menu.

**Comment by rentalhost** [comment]
@phiterf Sure, please, fill an issue, so I can control it better.

**Comment by youyi1314** [comment]
Why after i update to 0.3.3 but i still received error:

> com.jetbrains.php.lang.psi.elements.Method.getReturnType()Lcom/intellij/psi/PsiElement;
> java.lang.NoSuchMethodError: com.jetbrains.php.lang.psi.elements.Method.getReturnType()Lcom/intellij/psi/PsiElement;
> 	at net.rentalhost.idea.laravelInsight.fluent.UsingAsTypeInspection$1.visitPhpMethod(UsingAsTypeInspection.java:34)
> 	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:86)
> 	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
> 	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:286)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:254)
> 	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
> 	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
> 	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
> 	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:96)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
> 	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
> 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> 
> 
> java.lang.NoSuchMethodError: com.jetbrains.php.lang.psi.elements.Method.getReturnType()Lcom/intellij/psi/PsiElement;
> 	at net.rentalhost.idea.laravelInsight.fluent.UsingAsTypeInspection$1.visitPhpMethod(UsingAsTypeInspection.java:34)
> 	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:86)
> 	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
> 	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:286)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:254)
> 	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1122)
> 	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
> 	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
> 	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:96)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
> 	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
> 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
> 	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
> 	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
> 	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
> 	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
> 	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
> 	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
> 	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:257)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:227)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
> 	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
> 	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:437)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:405)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
> 	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> 
> 
> java.lang.NoSuchMethodError: com.jetbrains.php.lang.psi.elements.Method.getReturnType()Lcom/intellij/psi/PsiElement;
> 	at net.rentalhost.idea.laravelInsight.fluent.UsingAsTypeInspection$1.visitPhpMethod(UsingAsTypeInspection.java:34)
> 	at com.jetbrains.php.lang.psi.elements.impl.MethodImpl.accept(MethodImpl.java:86)
> 	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
> 	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:286)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:254)
> 	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:133)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1122)
> 	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:105)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
> 	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:116)
> 	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:96)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
> 	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
> 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
> 	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
> 	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
> 	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:390)
> 	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
> 	at java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2616)
> 	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:65)
> 	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:257)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:227)
> 	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
> 	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:83)
> 	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:437)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:543)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:405)
> 	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
> 	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
> 	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
> 	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by rentalhost** [comment]
@youyi1314 Thanks for reporting. I have send a new version to Jetbrains repository: 0.3.3.1, but it yet was not accepted. This version should fix this problem (see this [comment](https://github.com/rentalhost/laravel-insight/issues/30#issuecomment-352738645)).

**Comment by youyi1314** [comment]
@rentalhost ow~ thanks for your update =)
